apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-rabbitmq-0
  namespace: tappit-v2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: imported-rabbitmq-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
